language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: nSzAlS3MNaoybvyHpt/BzoTaO7G1nyVm6if3XGBi8+dUe5LFUYXc7zG2k4K5Ki1pxiCwMAICQZPIkNKbyDZMi3igbWcIb/b8Or2pmi9GYVCSRVKrsEK17CpAGlC2lmOcHUImDykTB+7TG7IYMmf0D++/6cHWHl3rVdzta1ziw27et0XGvsdGRld5sXsPDBpLSN3iakpvJoFGl/bo4kFXGFIhYVbGAZP8yLKbFfWPWmGWhr1BnSqvSm4CVL5pZAMutw/meKhPYtAm3IzzoyP1lA1rKngTSnsl0V5H1r8g0YfDXNNAfb/krGD1+s/+MoOwkMBvHb9MYqKap/w6I58dVgulFUUCOXMCMXT+W+1UT1bUTTfBG5YJ9WFmyX6SRGhFqiKnbcYXDuUxnf+ZDx9hYdabDVh16NGpwU3Fv4IAno4qmc1A6ueiMsJhH67/iPild0UOpRJBKVxJToUfCsdZ1LL5tRRaNAATiyD0vNJibWEng8dRvN4sSRi2BaqNqBhIvlBeuSysiaJZ+F2KDgWhwGQef9xW7/GzUGWFCYWnMi2N77g5P4iktzB+96M70zX4NkqWsIrMiEWbkyksS8GgdZxM/NAghBZpCRVhtSrL+cIru1JmO/U7FkeMJFBaxNcsHAk/E3G4uZX50oosruZqM8eBiYIOHw+eIZq7BoYNvO0=
